POST http://{{adminUrl}}/words/bulk
Content-Type: application/json

{
  "content": "hellox, what is your name"
}

###
###not working ,looks like admin.last6.local must be registered somewhere
GET http://{{adminUrl}}/words?x=22&y=55
Content-Type: application/xhtml+xml

###
